import '../sass/index.scss';
import '../../js/canvas.js';
import '../css/canvas.css';
import '../js/burger.js';
import '../js/typing.js';
import '../js/slider.js';
import '../js/certificatesGallery.js';
import '../js/whyWorth.js';
import '../js/scroller.js';